/**
 * PDF export helpers for PickListFTC.
 * Uses dynamic imports so jsPDF is never bundled for SSR.
 */

import type { TeamReport, TeamEventStats2025 } from "@/lib/types";
import type { ScoutNote } from "@/lib/notes";

// ── Local types ───────────────────────────────────────────────────────────────

export interface PickListEntry {
  teamNumber: number;
  teamName: string;
  opr: number;
  notes: string;
  picked: boolean;
}

// ── Color palette (RGB tuples) ────────────────────────────────────────────────

type RGB = [number, number, number];

const C = {
  accent:      [59,  130, 246] as RGB, // blue-500
  navy:        [15,  30,  70]  as RGB, // dark header for report
  black:       [17,  24,  39]  as RGB,
  darkGray:    [55,  65,  81]  as RGB,
  gray:        [107, 114, 128] as RGB,
  lightGray:   [229, 231, 235] as RGB,
  veryLight:   [249, 250, 251] as RGB,
  white:       [255, 255, 255] as RGB,
  takenGray:   [156, 163, 175] as RGB,
  greenBg:     [236, 253, 245] as RGB, // emerald-50
  amberBg:     [255, 251, 235] as RGB, // amber-50
  redBg:       [254, 242, 242] as RGB, // red-50
};

// ── Shared constants ──────────────────────────────────────────────────────────

const MARGIN   = 14;  // mm
const FOOTER_H = 16;  // mm reserved at bottom for footer

// ── Timestamp helpers ─────────────────────────────────────────────────────────

function tsFile(d: Date): string {
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}`;
}

function tsDisplay(d: Date): string {
  return d.toLocaleDateString("en-US", {
    month: "long", day: "numeric", year: "numeric",
  }) + " at " + d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
}

// ── Footer drawer (call after all content is placed) ─────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function addFooters(doc: any, timestamp: string) {
  const totalPages = doc.getNumberOfPages();
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Separator line
    doc.setDrawColor(...C.lightGray);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, ph - FOOTER_H + 2, pw - MARGIN, ph - FOOTER_H + 2);

    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...C.gray);

    // Left: branding
    doc.text("Generated by PickListFTC — picklistftc.com", MARGIN, ph - FOOTER_H + 7);

    // Center: page number
    doc.text(`Page ${i} of ${totalPages}`, pw / 2, ph - FOOTER_H + 7, { align: "center" });

    // Right: attribution + timestamp
    doc.text(`Built by First Try #21364  ·  ${timestamp}`, pw - MARGIN, ph - FOOTER_H + 7, { align: "right" });
  }
}

// ── Section heading helper ────────────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function sectionHeading(doc: any, text: string, x: number, y: number, contentWidth: number) {
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...C.gray);
  doc.text(text.toUpperCase(), x, y);
  doc.setDrawColor(...C.lightGray);
  doc.setLineWidth(0.3);
  doc.line(x + doc.getTextWidth(text.toUpperCase()) + 3, y - 0.5, x + contentWidth, y - 0.5);
}

// ── Page overflow helper ──────────────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function ensureSpace(doc: any, y: number, needed: number, margin = MARGIN): number {
  const ph = doc.internal.pageSize.getHeight();
  if (y + needed > ph - FOOTER_H - 4) {
    doc.addPage();
    return margin + 4;
  }
  return y;
}

// ─────────────────────────────────────────────────────────────────────────────
// Pick List PDF
// ─────────────────────────────────────────────────────────────────────────────

export async function exportPickListPDF(
  eventName: string,
  eventCode: string,
  entries: PickListEntry[]
) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const jsPDF = (await import("jspdf") as any).default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const autoTable = (await import("jspdf-autotable") as any).default;

  const now = new Date();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const pw = doc.internal.pageSize.getWidth();

  const active = entries.filter((e) => !e.picked);
  const taken  = entries.filter((e) => e.picked);

  // ── Header bar ──
  const BAR_H = 20;
  doc.setFillColor(...C.accent);
  doc.rect(0, 0, pw, BAR_H, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...C.white);
  doc.text("PickListFTC", MARGIN, 13);

  // Filename-safe date on right
  doc.setFontSize(8);
  doc.setTextColor(200, 220, 255);
  doc.text(tsDisplay(now), pw - MARGIN, 13, { align: "right" });

  // ── Event info block ──
  let y = BAR_H + 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...C.black);
  doc.text(eventName, MARGIN, y);
  y += 5.5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.gray);
  doc.text(`Event Code: ${eventCode.toUpperCase()}`, MARGIN, y);
  doc.text(`${entries.length} team${entries.length !== 1 ? "s" : ""} ranked  ·  ${active.length} active, ${taken.length} taken`, pw - MARGIN, y, { align: "right" });
  y += 7;

  // ── Active pick list table ──
  const takenActiveSet = new Set<number>(); // row indices within the ACTIVE table that are taken — N/A here

  autoTable(doc, {
    startY: y,
    head: [["#", "Team", "Name", "OPR", "Notes"]],
    body: active.map((e, i) => [
      `${i + 1}`,
      String(e.teamNumber),
      e.teamName,
      e.opr.toFixed(1),
      e.notes,
    ]),
    styles: {
      fontSize: 9,
      cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
      textColor: C.black,
      lineColor: C.lightGray,
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: C.accent,
      textColor: C.white,
      fontStyle: "bold",
      fontSize: 8,
    },
    alternateRowStyles: {
      fillColor: C.veryLight,
    },
    columnStyles: {
      0: { cellWidth: 12, halign: "center", textColor: C.gray },
      1: { cellWidth: 20, fontStyle: "bold", halign: "center" },
      2: { cellWidth: "auto" },
      3: { cellWidth: 22, halign: "right", font: "courier" },
      4: { cellWidth: 50, textColor: C.darkGray },
    },
    margin: { left: MARGIN, right: MARGIN, bottom: FOOTER_H + 2 },
  });

  // ── Taken section (if any) ──
  if (taken.length > 0) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 10;
    y = ensureSpace(doc, y, 30);

    sectionHeading(doc, "Taken by Other Alliances", MARGIN, y, pw - MARGIN * 2);
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [["", "Team", "Name", "OPR", "Notes"]],
      body: taken.map((e) => [
        "—",
        String(e.teamNumber),
        e.teamName,
        e.opr.toFixed(1),
        e.notes,
      ]),
      styles: {
        fontSize: 9,
        cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
        textColor: C.takenGray,
        lineColor: C.lightGray,
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: C.lightGray,
        textColor: C.gray,
        fontStyle: "bold",
        fontSize: 8,
      },
      columnStyles: {
        0: { cellWidth: 12, halign: "center" },
        1: { cellWidth: 20, fontStyle: "bold", halign: "center" },
        2: { cellWidth: "auto" },
        3: { cellWidth: 22, halign: "right", font: "courier" },
        4: { cellWidth: 50 },
      },
      // Strikethrough line through each taken row
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      didDrawCell: (data: any) => {
        if (data.section === "body") {
          const midY = data.cell.y + data.cell.height / 2;
          doc.setDrawColor(...C.takenGray);
          doc.setLineWidth(0.25);
          doc.line(data.cell.x + 1, midY, data.cell.x + data.cell.width - 1, midY);
        }
      },
      margin: { left: MARGIN, right: MARGIN, bottom: FOOTER_H + 2 },
    });
  }

  addFooters(doc, tsDisplay(now));
  doc.save(`${eventCode.toUpperCase()}_PickList_${tsFile(now)}.pdf`);
}

// ─────────────────────────────────────────────────────────────────────────────
// Scout Report PDF
// ─────────────────────────────────────────────────────────────────────────────

function buildSummaryText(report: TeamReport): string {
  const eventsWithStats = report.events.filter((e) => e.stats !== null);
  const count = eventsWithStats.length;
  if (count === 0) return "No event data available for this season.";

  const stats = eventsWithStats.map((e) => e.stats as TeamEventStats2025);

  const bestTotal = Math.max(...stats.map((s) => s.opr.totalPointsNp));
  const bestAuto  = Math.max(...stats.map((s) => s.opr.autoPoints));
  const bestDc    = Math.max(...stats.map((s) => s.opr.dcPoints));

  const avgAutoRatio = stats.reduce((s, st) => s + st.opr.autoPoints / (st.opr.totalPointsNp || 1), 0) / count;
  const avgDcRatio   = stats.reduce((s, st) => s + st.opr.dcPoints  / (st.opr.totalPointsNp || 1), 0) / count;

  const classification = avgAutoRatio > avgDcRatio * 1.3
    ? "auto-first"
    : avgDcRatio > avgAutoRatio * 1.3
      ? "DC-first"
      : "balanced";

  const avgDev   = stats.reduce((s, st) => s + st.dev.totalPointsNp, 0) / count;
  const avgTotal = stats.reduce((s, st) => s + st.avg.totalPointsNp, 0) / count;
  const isConsistent = avgDev < avgTotal * 0.25;

  const classLabels: Record<string, string> = {
    "auto-first": "an auto-first team, generating most of their scoring in autonomous",
    "DC-first":   "a DC-first team, excelling during driver-controlled play",
    "balanced":   "a balanced team with well-distributed scoring across game phases",
  };

  const parts = [
    `Team ${report.number} has competed in ${count} event${count !== 1 ? "s" : ""} this season, achieving a peak OPR of ${bestTotal.toFixed(1)} (Auto: ${bestAuto.toFixed(1)}, DC: ${bestDc.toFixed(1)}).`,
    `They are ${classLabels[classification]}.`,
  ];

  if (isConsistent) parts.push("They are notably consistent, with low score variance across matches.");

  const avgMovement = stats.reduce((s, st) => s + (st.avg.movementRp ?? 0), 0) / count;
  const avgGoal     = stats.reduce((s, st) => s + (st.avg.goalRp ?? 0), 0) / count;
  const avgPattern  = stats.reduce((s, st) => s + (st.avg.patternRp ?? 0), 0) / count;

  const rpNotes: string[] = [];
  if (avgMovement > 0.5) rpNotes.push(`movement (${(avgMovement * 100).toFixed(0)}%)`);
  if (avgGoal     > 0.5) rpNotes.push(`goal (${(avgGoal * 100).toFixed(0)}%)`);
  if (avgPattern  > 0.5) rpNotes.push(`pattern (${(avgPattern * 100).toFixed(0)}%)`);
  if (rpNotes.length > 0) parts.push(`Strong RP achievement rates: ${rpNotes.join(", ")}.`);

  return parts.join(" ");
}

export async function exportScoutReportPDF(
  report: TeamReport,
  notes: ScoutNote[]
) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const jsPDF = (await import("jspdf") as any).default;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const autoTable = (await import("jspdf-autotable") as any).default;

  const now = new Date();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const pw = doc.internal.pageSize.getWidth();
  const cw = pw - MARGIN * 2; // content width

  const eventsWithStats = report.events
    .filter((e) => e.stats !== null)
    .sort((a, b) => new Date(a.event.start).getTime() - new Date(b.event.start).getTime());

  const allStats = eventsWithStats.map((e) => e.stats as TeamEventStats2025);

  // ── Header bar ──
  const BAR_H = 34;
  doc.setFillColor(...C.navy);
  doc.rect(0, 0, pw, BAR_H, "F");

  // Accent stripe at bottom of bar
  doc.setFillColor(...C.accent);
  doc.rect(0, BAR_H - 2, pw, 2, "F");

  // Team number (large)
  doc.setFont("courier", "bold");
  doc.setFontSize(28);
  doc.setTextColor(...C.white);
  doc.text(String(report.number), MARGIN, 22);

  // Team name + school
  const teamNumWidth = doc.getTextWidth(String(report.number));
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(report.name, MARGIN + teamNumWidth + 5, 17);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(180, 200, 240);
  const schoolLine = [report.schoolName, report.rookieYear > 0 ? `Rookie ${report.rookieYear}` : ""].filter(Boolean).join("  ·  ");
  doc.text(schoolLine, MARGIN + teamNumWidth + 5, 24);

  // Season label top-right
  doc.setFontSize(8);
  doc.setTextColor(150, 180, 230);
  doc.text("DECODE 2025-2026", pw - MARGIN, 10, { align: "right" });
  doc.text("Season Scout Report", pw - MARGIN, 16, { align: "right" });
  doc.setTextColor(120, 150, 200);
  doc.text(tsDisplay(now), pw - MARGIN, 22, { align: "right" });

  let y = BAR_H + 10;

  // ── Executive Summary ──
  sectionHeading(doc, "Executive Summary", MARGIN, y, cw);
  y += 5;

  const summaryText = buildSummaryText(report);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...C.darkGray);
  const summaryLines = doc.splitTextToSize(summaryText, cw);
  summaryLines.forEach((line: string) => {
    y = ensureSpace(doc, y, 6);
    doc.text(line, MARGIN, y);
    y += 5;
  });
  y += 4;

  // ── Quick Stats box ──
  if (report.quickStats) {
    y = ensureSpace(doc, y, 28);
    sectionHeading(doc, "Quick Stats", MARGIN, y, cw);
    y += 5;

    const qs = report.quickStats;
    const stats = [
      { label: "Total OPR",  value: qs.tot.value.toFixed(1), rank: qs.tot.rank },
      { label: "Auto OPR",   value: qs.auto.value.toFixed(1), rank: qs.auto.rank },
      { label: "DC OPR",     value: qs.dc.value.toFixed(1),   rank: qs.dc.rank },
      { label: "Endgame",    value: qs.eg.value.toFixed(1),   rank: qs.eg.rank },
    ];

    const cellW = cw / 4;
    stats.forEach((s, i) => {
      const x = MARGIN + i * cellW;

      // Box
      doc.setFillColor(...C.veryLight);
      doc.setDrawColor(...C.lightGray);
      doc.setLineWidth(0.3);
      doc.rect(x, y, cellW - 2, 18, "FD");

      // Value
      doc.setFont("courier", "bold");
      doc.setFontSize(13);
      doc.setTextColor(...C.accent);
      doc.text(s.value, x + cellW / 2 - 1, y + 8, { align: "center" });

      // Label
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(...C.gray);
      doc.text(s.label, x + cellW / 2 - 1, y + 13, { align: "center" });

      // Rank
      doc.setFontSize(7);
      doc.setTextColor(...C.takenGray);
      doc.text(`#${s.rank} worldwide`, x + cellW / 2 - 1, y + 17, { align: "center" });
    });

    y += 23;
  }

  // ── Event History table ──
  y = ensureSpace(doc, y, 20);
  sectionHeading(doc, "Event History", MARGIN, y, cw);
  y += 5;

  autoTable(doc, {
    startY: y,
    head: [["Event", "Date", "Rank", "W-L-T", "OPR", "Avg Score", "Matches"]],
    body: eventsWithStats.map((entry) => {
      const s = entry.stats as TeamEventStats2025;
      const date = new Date(entry.event.start).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
      return [
        entry.event.name.length > 35 ? entry.event.name.slice(0, 33) + "…" : entry.event.name,
        date,
        `#${s.rank}`,
        `${s.wins}-${s.losses}-${s.ties}`,
        s.opr.totalPointsNp.toFixed(1),
        s.avg.totalPointsNp.toFixed(1),
        String(s.qualMatchesPlayed),
      ];
    }),
    styles: {
      fontSize: 8.5,
      cellPadding: { top: 2.5, bottom: 2.5, left: 3, right: 3 },
      textColor: C.black,
      lineColor: C.lightGray,
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: C.navy,
      textColor: C.white,
      fontStyle: "bold",
      fontSize: 7.5,
    },
    alternateRowStyles: { fillColor: C.veryLight },
    columnStyles: {
      0: { cellWidth: "auto" },
      1: { cellWidth: 28 },
      2: { cellWidth: 16, halign: "center" },
      3: { cellWidth: 22, halign: "center", font: "courier" },
      4: { cellWidth: 20, halign: "right",  font: "courier" },
      5: { cellWidth: 22, halign: "right",  font: "courier" },
      6: { cellWidth: 18, halign: "center" },
    },
    margin: { left: MARGIN, right: MARGIN, bottom: FOOTER_H + 2 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 10;

  // ── Strengths & Analysis ──
  if (allStats.length > 0) {
    y = ensureSpace(doc, y, 50);
    sectionHeading(doc, "Strengths & Analysis", MARGIN, y, cw);
    y += 5;

    // Classification
    const avgAuto = allStats.reduce((s, st) => s + st.opr.autoPoints, 0) / allStats.length;
    const avgDc   = allStats.reduce((s, st) => s + st.opr.dcPoints, 0) / allStats.length;
    let classLabel: string;
    let classColor: RGB;
    if (avgAuto > avgDc * 1.3) {
      classLabel = "Auto-first";
      classColor = [59, 130, 246];
    } else if (avgDc > avgAuto * 1.3) {
      classLabel = "DC-first";
      classColor = [20, 184, 166];
    } else {
      classLabel = "Balanced";
      classColor = [245, 158, 11];
    }

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...classColor);
    doc.text(`Team Classification: ${classLabel}`, MARGIN, y);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(...C.gray);
    doc.setFontSize(8.5);
    const classDesc = classLabel === "Auto-first"
      ? "Most scoring comes from autonomous — strong first-pick for auto reliability."
      : classLabel === "DC-first"
        ? "Excels during driver-controlled play — ideal partner for DC scoring power."
        : "Well-distributed scoring across both game phases — versatile alliance partner.";
    doc.text(classDesc, MARGIN, y + 4.5);
    y += 11;

    // RP Profile
    y = ensureSpace(doc, y, 20);
    const avgMovement = allStats.reduce((s, st) => s + (st.avg.movementRp ?? 0), 0) / allStats.length;
    const avgGoal     = allStats.reduce((s, st) => s + (st.avg.goalRp ?? 0), 0) / allStats.length;
    const avgPattern  = allStats.reduce((s, st) => s + (st.avg.patternRp ?? 0), 0) / allStats.length;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...C.black);
    doc.text("RP Profile", MARGIN, y);
    y += 5;

    const rpItems = [
      { label: "Movement RP", val: avgMovement },
      { label: "Goal RP",     val: avgGoal },
      { label: "Pattern RP",  val: avgPattern },
    ];

    rpItems.forEach((item) => {
      const pct = (item.val * 100).toFixed(0) + "%";
      const color: RGB = item.val >= 0.6 ? [16, 185, 129] : item.val >= 0.3 ? [245, 158, 11] : [239, 68, 68];

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(...C.darkGray);
      doc.text(item.label, MARGIN + 2, y);

      doc.setFont("courier", "bold");
      doc.setTextColor(...color);
      doc.text(pct, MARGIN + 45, y);
      y += 4.5;
    });
    y += 4;

    // Consistency
    y = ensureSpace(doc, y, 14);
    const avgDev   = allStats.reduce((s, st) => s + st.dev.totalPointsNp, 0) / allStats.length;
    const avgTotal = allStats.reduce((s, st) => s + st.avg.totalPointsNp, 0) / allStats.length;
    const devRatio = avgTotal > 0 ? avgDev / avgTotal : 0;
    const consLabel = devRatio < 0.20 ? "Consistent" : devRatio < 0.35 ? "Average" : "Inconsistent";
    const consColor: RGB = devRatio < 0.20 ? [16, 185, 129] : devRatio < 0.35 ? [245, 158, 11] : [239, 68, 68];

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...C.black);
    doc.text("Consistency", MARGIN, y);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...consColor);
    doc.text(consLabel, MARGIN + 28, y);

    doc.setTextColor(...C.gray);
    doc.text(`  (avg deviation: ${avgDev.toFixed(1)} pts over ${allStats.length} event${allStats.length !== 1 ? "s" : ""})`, MARGIN + 28 + doc.getTextWidth(consLabel), y);
    y += 9;

    // Penalty profile
    const hasPenalty = allStats.some((s) => s.avg.penaltyPointsCommitted !== undefined);
    if (hasPenalty) {
      y = ensureSpace(doc, y, 14);
      const avgPenalty = allStats.reduce((s, st) => s + (st.avg.penaltyPointsCommitted ?? 0), 0) / allStats.length;
      const { label: riskLabel, color: riskColor } = avgPenalty < 5
        ? { label: "Low risk", color: [16, 185, 129] as RGB }
        : avgPenalty <= 15
          ? { label: "Moderate risk", color: [245, 158, 11] as RGB }
          : { label: "High risk", color: [239, 68, 68] as RGB };

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...C.black);
      doc.text("Penalty Profile", MARGIN, y);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(...riskColor);
      doc.text(riskLabel, MARGIN + 35, y);

      doc.setTextColor(...C.gray);
      doc.text(`  (avg ${avgPenalty.toFixed(1)} pts/match committed)`, MARGIN + 35 + doc.getTextWidth(riskLabel), y);
      y += 9;
    }
  }

  // ── Scout Notes ──
  y = ensureSpace(doc, y, 20);
  y += 4;
  sectionHeading(doc, "Scout Notes", MARGIN, y, cw);
  y += 5;

  if (notes.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(...C.gray);
    doc.text("No scout notes recorded.", MARGIN, y);
    y += 8;
  } else {
    for (const note of notes) {
      const noteHeight = 8 + (note.text ? Math.ceil(doc.splitTextToSize(note.text, cw - 6).length * 4.5) : 0) + (note.tags.length > 0 ? 6 : 0);
      y = ensureSpace(doc, y, noteHeight + 4);

      // Note card background
      doc.setFillColor(...C.veryLight);
      doc.setDrawColor(...C.lightGray);
      doc.setLineWidth(0.2);
      doc.roundedRect(MARGIN, y, cw, noteHeight, 1.5, 1.5, "FD");

      let ny = y + 4.5;

      if (note.text) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        doc.setTextColor(...C.darkGray);
        const textLines: string[] = doc.splitTextToSize(note.text, cw - 6);
        textLines.forEach((line: string) => {
          doc.text(line, MARGIN + 3, ny);
          ny += 4.5;
        });
      }

      if (note.tags.length > 0) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        doc.setTextColor(...C.accent);
        doc.text(note.tags.join("  ·  "), MARGIN + 3, ny);
        ny += 5;
      }

      // Timestamp
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(...C.takenGray);
      doc.text(
        new Date(note.timestamp).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }),
        pw - MARGIN - 3, y + noteHeight - 3,
        { align: "right" }
      );

      y += noteHeight + 4;
    }
  }

  addFooters(doc, tsDisplay(now));
  doc.save(`Team_${report.number}_ScoutReport_${tsFile(now)}.pdf`);
}
